local wezterm = require("wezterm")

return {
  enable_wayland = true,
  keys = {
    { key = "C", mods = "CTRL|SHIFT", action = wezterm.action.CopyTo("Clipboard") },
    { key = "V", mods = "CTRL|SHIFT", action = wezterm.action.PasteFrom("Clipboard") },
    { key = "Insert", mods = "SHIFT", action = wezterm.action.PasteFrom("Clipboard") },
  },
  font = wezterm.font_with_fallback({
    "CaskaydiaCove NF",
    "FiraCode Nerd Font",
    "Hack Nerd Font",
    "JetBrainsMono Nerd Font",
    "SourceCodePro Nerd Font",
    "SF Mono",
    "Monaco",
    "Inconsolata",
    "Fira Code",
    "Consolas",
    "Terminus",
    "Andale Mono",
    "Lucida Console",
    "Liberation Mono",
    "Bitstream Vera Sans Mono",
    "Courier New",
    "monospace",
  }),
  font_size = 13,
  colors = {
    foreground = "#e0def4",
    background = "#191724",
    cursor_bg = "#e0def4",
    cursor_fg = "#191724",
    cursor_border = "#e0def4",
    selection_bg = "#403d52",
    selection_fg = "#e0def4",
    ansi = {
      "#26233a",
      "#eb6f92",
      "#31748f",
      "#f6c177",
      "#9ccfd8",
      "#c4a7e7",
      "#ebbcba",
      "#e0def4",
    },
    brights = {
      "#6e6a86",
      "#eb6f92",
      "#31748f",
      "#f6c177",
      "#9ccfd8",
      "#c4a7e7",
      "#ebbcba",
      "#e0def4",
    },
  },
  default_cursor_style = "SteadyBlock",
  window_padding = {
    left = 8,
    right = 8,
    top = 8,
    bottom = 8,
  },
  window_decorations = "NONE",
  hide_tab_bar_if_only_one_tab = true,
  hide_mouse_cursor_when_typing = true,
}
